return {
  --   {
  --     'ThePrimeagen/harpoon',
  --     branch = 'harpoon2',
  --     dependencies = { 'nvim-lua/plenary.nvim' },
  --     lazy = false,
  --     config = function()
  --       local harpoon = require 'harpoon'
  --       harpoon:setup {
  --         settings = {
  --           save_on_toggle = true,
  --           sync_on_ui_close = true,
  --         },
  --       }
  --       vim.keymap.set('n', '<leader>a', function()
  --         harpoon:list():add()
  --       end, { desc = 'Add to harpoon' })
  --       vim.keymap.set('n', '<C-e>', function()
  --         harpoon.ui:toggle_quick_menu(harpoon:list())
  --       end, { desc = 'Harpoon quick menu' })
  --       vim.keymap.set('n', '<leader>1', function()
  --         harpoon:list():select(1)
  --       end, { desc = 'Select first harpoon' })
  --       vim.keymap.set('n', '<leader>2', function()
  --         harpoon:list():select(2)
  --       end, { desc = 'Select second harpoon' })
  --       vim.keymap.set('n', '<leader>3', function()
  --         harpoon:list():select(3)
  --       end, { desc = 'Select third harpoon' })
  --       vim.keymap.set('n', '<leader>4', function()
  --         harpoon:list():select(4)
  --       end, { desc = 'Select fourth harpoon' })
  --       vim.keymap.set('n', '<leader>5', function()
  --         harpoon:list():select(5)
  --       end, { desc = 'Select fifth harpoon' })
  --       vim.keymap.set('n', '<leader>6', function()
  --         harpoon:list():select(6)
  --       end, { desc = 'Select sixth harpoon' })
  --     end,
  --   },
}
